# Generated by Django 3.2 on 2025-07-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('email', 'почта'), ('sms', 'сообщение'), ('web', 'веб-уведомление')], max_length=15, verbose_name='Тип'),
        ),
    ]
